# -*- coding: utf-8 -*-
"""Platypus_Premium_(1) (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AnpoFu8GPjMYTVSWoYRJgf0LvUta_tXM

# 🦫 Platypus
### Think in Documents.

A premium, production-grade RAG (Retrieval-Augmented Generation) chat application for PDFs.

**This notebook upgrades the existing working RAG pipeline into a flagship-quality product experience.**
The retrieval core — PDF extraction, word-based chunking (200 words / 40 overlap), `all-MiniLM-L6-v2`
embeddings, ChromaDB storage, and `HuggingFaceH4/zephyr-7b-beta` generation — is preserved exactly as it
worked before. What's new:

- **Redesigned UI**: premium dark-first theme (20/55/25 sidebar/conversation/preview layout),
  optional light-mode toggle, glass-tasteful surfaces, micro-animations, and a distinct
  electric-indigo/soft-cyan identity.
- **Document filtering, fixed**: selecting a document now actually scopes retrieval to it (previously
  every query searched the whole collection regardless of what was selected). "Entire Library" mode
  searches across everything, clearly labeled.
- **Smart, clickable prompt chips** that fill *and send* automatically.
- **Redesigned source/citation cards** with a similarity-score bar and confidence badge.
- **Real PDF highlighting** on citation click and search-result click.
- **Search inside PDF**, scoped to the current document or the whole library.
- **Conversation memory** — follow-ups like "explain it more simply" resolve against recent turns.
- **Export** conversations to Markdown or PDF, with sources and timestamps.

Run the cells top to bottom. A GPU runtime (Runtime → Change runtime type → GPU) is strongly recommended —
Zephyr-7B is large and will be very slow on CPU.

## Install Libraries

Same dependencies as before, plus `PyMuPDF` (for rendering PDF pages into the preview panel and drawing
citation highlights) and `Pillow` (image handling for that preview).
"""

!pip install -q PyPDF2 sentence-transformers chromadb transformers accelerate bitsandbytes gradio torch PyMuPDF Pillow

"""## Imports"""

import os
import re
import uuid
import html
import warnings
import threading
import textwrap
from datetime import datetime
from functools import partial
from dataclasses import dataclass, field
from typing import List, Dict, Tuple, Optional, Generator

import torch
import gradio as gr
import chromadb
from chromadb.config import Settings
from PyPDF2 import PdfReader
from PyPDF2.errors import PdfReadError
from sentence_transformers import SentenceTransformer
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TextIteratorStreamer,
)
import fitz  # PyMuPDF
from PIL import Image

warnings.filterwarnings("ignore")

"""## Design Tokens & Branding

The Platypus visual identity in one place: color palette, typography, and the logo mark. Everything else
(CSS, HTML fragments) is built from these constants so the look stays consistent, and is easy to retheme.

Palette rationale: an electric-indigo primary with a soft-cyan secondary accent (distinct from ChatGPT's
green and Claude's orange) on a near-black canvas, with a warm amber reserved *only* for citation
highlights. Quiet, confident, and premium — closer to the restraint of Linear/Notion/Arc than to a
generic purple-gradient AI app, without copying any one of them.
"""

PLATYPUS_NAME = "Platypus"
PLATYPUS_TAGLINE = "Think in Documents."

# ---------------------------------------------------------------------------
# Design tokens. A premium dark theme is the default; a lighter theme is
# toggled at runtime by adding/removing a `p-light` class on <body> (see CSS +
# JS below). Palette: electric indigo primary with a soft-cyan secondary
# accent on a near-black canvas — deliberately not another purple-gradient AI
# app, and not a copy of any single inspiration.
# ---------------------------------------------------------------------------

COLOR_BG = "#0D1117"
COLOR_SURFACE = "#1C2128"
COLOR_SIDEBAR = "#0B0E14"
COLOR_SIDEBAR_SOFT = "#161B22"
COLOR_BORDER = "rgba(255,255,255,0.06)"
COLOR_TEXT = "#E6E8EF"
COLOR_TEXT_MUTED = "#8B93A7"
COLOR_PRIMARY = "#6366F1"          # electric indigo
COLOR_PRIMARY_SOFT = "rgba(99,102,241,0.16)"
COLOR_ACCENT_BLUE = "#4F8CFF"      # supporting blue accent
COLOR_ACCENT_CYAN = "#67E8F9"      # soft cyan accent
COLOR_HIGHLIGHT = "#FDE68A"
COLOR_DANGER = "#F87171"           # soft red
COLOR_SUCCESS = "#34D399"          # emerald

# Light-theme overrides (applied via body.p-light in CSS)
LIGHT_BG = "#F6F7FB"
LIGHT_SURFACE = "#FFFFFF"
LIGHT_BORDER = "#E7E9F1"
LIGHT_TEXT = "#12131A"
LIGHT_TEXT_MUTED = "#6B7086"
LIGHT_PRIMARY_SOFT = "#EEEEFE"

# A minimal, geometric platypus mark: a rounded badge, a body arc, and a flattened bill.
# Monochrome via currentColor so it can sit on both light and dark backgrounds.
PLATYPUS_LOGO_SVG = """
<svg width="34" height="34" viewBox="0 0 40 40" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect width="40" height="40" rx="12" fill="url(#platypus-grad)"/>
  <path d="M10 24c0-6 5-10.5 12-10.5 5 0 9 2 9 5 0 2.4-2.3 3.7-5.4 3.9.9 1 1.4 2.3 1.4 3.6 0 3.4-3.7 6-9 6-4.9 0-8-3-8-8.5z"
        fill="white" fill-opacity="0.95"/>
  <ellipse cx="27.5" cy="17.6" rx="4.6" ry="2.6" fill="white" fill-opacity="0.95"/>
  <circle cx="15.5" cy="21" r="1.3" fill="#11131A"/>
  <defs>
    <linearGradient id="platypus-grad" x1="0" y1="0" x2="40" y2="40" gradientUnits="userSpaceOnUse">
      <stop stop-color="#6366F1"/>
      <stop offset="1" stop-color="#67E8F9"/>
    </linearGradient>
  </defs>
</svg>
"""

"""## Custom CSS

One consolidated stylesheet: typography (Inter), the three-panel layout, chat bubbles, source cards,
the sidebar, loading states, and small motion touches. Passed into `gr.Blocks(css=...)`.
"""

PLATYPUS_CSS = f"""
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap');

:root {{
  --p-bg: {COLOR_BG};
  --p-surface: {COLOR_SURFACE};
  --p-border: {COLOR_BORDER};
  --p-text: {COLOR_TEXT};
  --p-text-muted: {COLOR_TEXT_MUTED};
  --p-primary: {COLOR_PRIMARY};
  --p-primary-soft: {COLOR_PRIMARY_SOFT};
  --p-accent-blue: {COLOR_ACCENT_BLUE};
  --p-accent-cyan: {COLOR_ACCENT_CYAN};
  --p-highlight: {COLOR_HIGHLIGHT};
  --p-danger: {COLOR_DANGER};
  --p-success: {COLOR_SUCCESS};
  --p-radius-lg: 20px;
  --p-radius-md: 14px;
  --p-radius-sm: 10px;
  --p-space-1: 8px;
  --p-space-2: 16px;
  --p-space-3: 24px;
  --p-ease: cubic-bezier(0.4, 0, 0.2, 1);
}}

/* Optional lighter theme, toggled via a `p-light` class on <body>. */
body.p-light {{
  --p-bg: {LIGHT_BG};
  --p-surface: {LIGHT_SURFACE};
  --p-border: {LIGHT_BORDER};
  --p-text: {LIGHT_TEXT};
  --p-text-muted: {LIGHT_TEXT_MUTED};
  --p-primary-soft: {LIGHT_PRIMARY_SOFT};
}}

* {{ font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif; }}

.gradio-container {{
  background: var(--p-bg) !important;
  max-width: 100% !important;
  transition: background 0.2s var(--p-ease);
}}

::-webkit-scrollbar {{ width: 8px; height: 8px; }}
::-webkit-scrollbar-thumb {{ background: var(--p-border); border-radius: 999px; }}
::-webkit-scrollbar-track {{ background: transparent; }}

/* ---------- Sidebar (20%) ---------- */
#platypus-sidebar {{
  background: {COLOR_SIDEBAR};
  border-radius: var(--p-radius-lg);
  padding: var(--p-space-3) var(--p-space-2);
  color: {COLOR_TEXT};
  min-height: 680px;
}}
#platypus-sidebar .p-logo-row {{
  display: flex; align-items: center; gap: 10px; margin-bottom: 4px;
}}
#platypus-sidebar .p-wordmark {{
  font-size: 20px; font-weight: 800; letter-spacing: -0.02em; color: #FFFFFF;
}}
#platypus-sidebar .p-tagline {{
  font-size: 12px; color: var(--p-text-muted); margin: 0 0 var(--p-space-3) 2px; font-style: italic;
}}
#platypus-sidebar .p-section-label {{
  font-size: 10.5px; font-weight: 700; letter-spacing: 0.09em; text-transform: uppercase;
  color: var(--p-text-muted); margin: var(--p-space-3) 2px var(--p-space-1) 2px;
}}
.p-theme-toggle {{
  cursor: pointer; border: 1px solid var(--p-border); background: {COLOR_SIDEBAR_SOFT};
  color: var(--p-text-muted); border-radius: 999px !important; font-size: 12px !important;
  transition: all 0.15s var(--p-ease);
}}
.p-theme-toggle:hover {{ border-color: var(--p-accent-cyan); color: #fff; }}

.p-doc-card {{
  background: {COLOR_SIDEBAR_SOFT}; border: 1px solid var(--p-border); border-radius: var(--p-radius-sm);
  padding: 10px 12px; margin-bottom: var(--p-space-1); transition: border-color 0.15s var(--p-ease);
}}
.p-doc-card.p-doc-active {{ border-color: var(--p-primary); box-shadow: 0 0 0 1px var(--p-primary) inset; }}
.p-doc-card .p-doc-name {{ font-size: 13px; font-weight: 600; color: {COLOR_TEXT}; overflow-wrap: anywhere; }}
.p-doc-card .p-doc-meta {{ font-size: 11px; color: var(--p-text-muted); margin-top: 2px; }}
.p-doc-card .p-doc-active-tag {{
  display: inline-block; font-size: 9.5px; font-weight: 700; letter-spacing: 0.05em;
  color: var(--p-accent-cyan); text-transform: uppercase; margin-top: 4px;
}}

.p-stat-grid {{ display: grid; grid-template-columns: 1fr 1fr; gap: var(--p-space-1); }}
.p-stat-box {{
  background: {COLOR_SIDEBAR_SOFT}; border: 1px solid var(--p-border); border-radius: var(--p-radius-sm);
  padding: 10px 12px; transition: border-color 0.15s var(--p-ease);
}}
.p-stat-box:hover {{ border-color: var(--p-primary); }}
.p-stat-box .p-stat-value {{ font-size: 18px; font-weight: 700; color: #FFFFFF; }}
.p-stat-box .p-stat-label {{ font-size: 10px; color: var(--p-text-muted); text-transform: uppercase; letter-spacing: 0.05em; }}
.p-gpu-dot {{ display: inline-block; width: 8px; height: 8px; border-radius: 50%; margin-right: 6px; }}

.p-scope-badge {{
  display: inline-flex; align-items: center; gap: 6px; font-size: 11.5px; font-weight: 600;
  padding: 6px 10px; border-radius: 999px; background: rgba(99,102,241,0.14); color: var(--p-accent-cyan);
  margin-top: 6px;
}}

/* ---------- Chat area (55%) ---------- */
#platypus-chat .message {{ border-radius: var(--p-radius-md) !important; }}
#platypus-chat {{
  background: var(--p-surface); border-radius: var(--p-radius-lg); border: 1px solid var(--p-border);
  transition: background 0.2s var(--p-ease), border-color 0.2s var(--p-ease);
}}

/* Issue 1: Fix placeholder color for both modes */
#platypus-chat .placeholder,
#platypus-chat .placeholder * {{
    color: var(--p-text) !important;
    opacity: 0.8 !important;
}}

.p-source-card {{
  display: inline-flex !important; flex-direction: column; align-items: flex-start !important; gap: 3px;
  background: var(--p-surface) !important; border: 1px solid var(--p-border) !important;
  border-radius: var(--p-radius-md) !important; padding: 10px 14px !important; text-align: left !important;
  box-shadow: 0 1px 2px rgba(0,0,0,0.16);
  transition: transform 0.15s var(--p-ease), box-shadow 0.15s var(--p-ease), border-color 0.15s var(--p-ease);
}}
.p-source-card:hover {{
  transform: translateY(-2px); border-color: var(--p-primary) !important;
  box-shadow: 0 12px 28px rgba(99,102,241,0.22);
}}

.p-chip-btn {{
  border-radius: var(--p-radius-md) !important; font-size: 12.5px !important; padding: 10px 16px !important;
  background: var(--p-primary-soft) !important; color: var(--p-accent-cyan) !important;
  border: 1px solid var(--p-border) !important; transition: all 0.15s var(--p-ease) !important;
  animation: p-chip-in 0.3s var(--p-ease) both;
}}

/* Issue 2: Prompt chips contrast in light mode */
body.p-light .p-chip-btn {{
  background: var(--p-surface) !important;
  color: var(--p-primary) !important;
  border-color: var(--p-primary) !important;
  font-weight: 600 !important;
}}

.p-chip-btn:hover {{
  background: var(--p-primary) !important; color: white !important; border-color: var(--p-primary) !important;
  transform: translateY(-2px); box-shadow: 0 8px 20px rgba(99,102,241,0.32);
}}
@keyframes p-chip-in {{
  from {{ opacity: 0; transform: translateY(4px) scale(0.97); }}
  to {{ opacity: 1; transform: translateY(0) scale(1); }}
}}

.p-confidence-badge {{
  display: inline-block; font-size: 10.5px; font-weight: 700; padding: 2px 9px; border-radius: 999px;
  letter-spacing: 0.02em;
}}
.p-conf-high {{ background: rgba(52,211,153,0.16); color: var(--p-success); }}
.p-conf-medium {{ background: rgba(245,158,11,0.16); color: #FBBF24; }}
.p-conf-low {{ background: rgba(248,113,113,0.16); color: var(--p-danger); }}

.p-score-bar {{ width: 60px; height: 4px; border-radius: 999px; background: var(--p-border); overflow: hidden; }}
.p-score-bar-fill {{ height: 100%; background: linear-gradient(90deg, var(--p-primary), var(--p-accent-cyan)); }}

mark.p-hl {{ background: var(--p-highlight); color: #12131A; padding: 0 2px; border-radius: 3px; }}

/* ---------- Right panel / PDF preview (25%) ---------- */
#platypus-preview {{
  background: var(--p-surface); border-radius: var(--p-radius-lg); border: 1px solid var(--p-border);
  padding: var(--p-space-2); min-height: 680px;
}}
.p-preview-header {{ font-size: 13px; font-weight: 700; color: var(--p-text); margin-bottom: 2px; }}
.p-preview-sub {{ font-size: 11.5px; color: var(--p-text-muted); margin-bottom: var(--p-space-1); }}

/* ---------- Buttons ---------- */
.p-primary-btn {{
  background: linear-gradient(135deg, var(--p-primary), var(--p-accent-blue)) !important;
  border: none !important; color: white !important;
  border-radius: var(--p-radius-sm) !important; font-weight: 600 !important;
  box-shadow: 0 4px 16px rgba(99,102,241,0.35) !important; transition: filter 0.15s var(--p-ease), transform 0.15s var(--p-ease) !important;
}}
.p-primary-btn:hover {{ filter: brightness(1.08); transform: translateY(-1px); }}
.p-ghost-btn {{
  background: transparent !important; border: 1px solid var(--p-border) !important;
  color: var(--p-text-muted) !important; border-radius: var(--p-radius-sm) !important;
  transition: all 0.15s var(--p-ease) !important;
}}
.p-ghost-btn:hover {{ border-color: var(--p-primary) !important; color: var(--p-primary) !important; }}

/* ---------- Loading / streaming ---------- */
.p-loading-row {{
  display: flex; align-items: center; gap: 8px; font-size: 13px; color: var(--p-text-muted);
}}
.p-loading-dot {{
  width: 7px; height: 7px; border-radius: 50%; background: var(--p-primary);
  animation: p-pulse 1s ease-in-out infinite;
}}
@keyframes p-pulse {{
  0%, 100% {{ opacity: 0.25; transform: scale(0.85); }}
  50% {{ opacity: 1; transform: scale(1.1); }}
}}
.p-stream-cursor {{
  display: inline-block; width: 2px; height: 1em; background: var(--p-primary);
  vertical-align: text-bottom; margin-left: 1px; animation: p-blink 0.9s step-end infinite;
}}
@keyframes p-blink {{ 0%, 50% {{ opacity: 1; }} 51%, 100% {{ opacity: 0; }} }}

.p-skeleton {{
  border-radius: var(--p-radius-sm); background: linear-gradient(90deg, var(--p-border) 25%, var(--p-surface) 50%, var(--p-border) 75%);
  background-size: 200% 100%; animation: p-shimmer 1.4s ease infinite; height: 14px; margin: 6px 0;
}}
@keyframes p-shimmer {{ 0% {{ background-position: 200% 0; }} 100% {{ background-position: -200% 0; }} }}

.p-success-flash {{
  color: var(--p-success); font-weight: 600; font-size: 12.5px;
  animation: p-fade-in-out 2.2s ease forwards;
}}
@keyframes p-fade-in-out {{
  0% {{ opacity: 0; }} 15% {{ opacity: 1; }} 80% {{ opacity: 1; }} 100% {{ opacity: 0; }}
}}

/* ---------- Search-in-PDF panel ---------- */
.p-search-result {{
  display: block !important; text-align: left !important; font-size: 12px !important;
  background: var(--p-primary-soft) !important; border: 1px solid transparent !important;
  color: var(--p-text) !important; border-radius: var(--p-radius-sm) !important; padding: 6px 10px !important;
}}
.p-search-result:hover {{ border-color: var(--p-primary) !important; }}

@media (max-width: 900px) {{
  #platypus-sidebar, #platypus-preview {{ min-height: unset; }}
}}
"""

# Small JS snippet toggled on the theme button click to flip a body class.
# Gradio runs this client-side via the `js=` kwarg on .click(...). Default
# theme is the premium dark palette; toggling adds the lighter override.
TOGGLE_DARK_JS = """
() => {
  document.body.classList.toggle('p-light');
}
"""

"""## Load Embedding Model

Unchanged from the original pipeline: `all-MiniLM-L6-v2`, loaded once and cached at module level.
"""

EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"

_embedding_model: Optional[SentenceTransformer] = None


def get_embedding_model() -> SentenceTransformer:
    """Return a cached SentenceTransformer instance, loading it once."""
    global _embedding_model
    if _embedding_model is None:
        print(f"Loading embedding model: {EMBEDDING_MODEL_NAME} ...")
        _embedding_model = SentenceTransformer(EMBEDDING_MODEL_NAME)
        print("Embedding model loaded.")
    return _embedding_model


embedding_model = get_embedding_model()

"""## Load Zephyr Model

Unchanged loading logic (same model, same 4-bit quantization on GPU, same CPU fallback). The only addition
is that we keep direct references to the underlying `_llm_model` / `_llm_tokenizer` so a later cell can
stream generation token-by-token — the original single-shot `pipeline()` call is still available too.
"""

import torch
from typing import Tuple
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

LLM_MODEL_NAME = "HuggingFaceH4/zephyr-7b-beta"

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

if DEVICE != "cuda":
    print(
        "⚠️  WARNING: No CUDA GPU detected. Zephyr-7B is a large model and will "
        "be extremely slow (or may run out of memory) on CPU. In Google Colab, "
        "go to Runtime > Change runtime type > select a GPU (e.g. T4) for a "
        "usable experience."
    )
else:
    print(f"CUDA GPU detected: {torch.cuda.get_device_name(0)}")

_llm_model = None
_llm_tokenizer = None


def get_llm() -> Tuple[AutoModelForCausalLM, AutoTokenizer]:
    """Return cached (model, tokenizer), loading them once."""
    global _llm_model, _llm_tokenizer

    if _llm_model is not None:
        return _llm_model, _llm_tokenizer

    print(f"Loading LLM: {LLM_MODEL_NAME} ...")

    _llm_tokenizer = AutoTokenizer.from_pretrained(LLM_MODEL_NAME)

    if DEVICE == "cuda":
        bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
        )
        _llm_model = AutoModelForCausalLM.from_pretrained(
            LLM_MODEL_NAME,
            quantization_config=bnb_config,
            device_map="auto",
        )
    else:
        _llm_model = AutoModelForCausalLM.from_pretrained(
            LLM_MODEL_NAME,
            torch_dtype=torch.float32,
        )
        _llm_model.to("cpu")

    print("LLM loaded.")
    return _llm_model, _llm_tokenizer


_llm_model, _llm_tokenizer = get_llm()

"""## App State & ChromaDB Setup

The original notebook tracked a single active PDF in `current_session`. Platypus supports multiple PDFs
at once, so this becomes a small in-memory registry (`app_state["documents"]`) plus **one shared Chroma
collection** for the session — every chunk is tagged with `doc_id` and `filename` metadata so retrieval
can span all uploaded documents and still report exactly which file/page an answer came from.

One deliberate, minimal change vs. the original: the collection is created with `hnsw:space="cosine"` so
that retrieval distances translate directly into a 0–1 similarity score, which we use for the confidence
badge. This does not change how retrieval behaves functionally (top-k nearest neighbor search).
"""

chroma_client = chromadb.Client(Settings(anonymized_telemetry=False))
COLLECTION_NAME = "platypus_collection"


@dataclass
class DocumentInfo:
    doc_id: str
    filename: str
    path: str
    num_pages: int
    num_chunks: int


app_state: Dict = {
    "documents": {},          # doc_id -> DocumentInfo
    "collection": None,
    "last_question": None,
    "last_sources": [],       # source dicts for the most recently answered turn
    "search_scope": "library",       # "library" (Entire Library) or "single" (Selected Document)
    "active_filter_doc_id": None,    # doc_id used as the retrieval filter when scope == "single"
    "conversation_log": [],   # [{question, answer, sources, confidence, timestamp}, ...] for export
    "last_search_query": "",
    "last_search_results": [],
}


def get_collection():
    if app_state["collection"] is None:
        app_state["collection"] = chroma_client.get_or_create_collection(
            name=COLLECTION_NAME,
            metadata={"hnsw:space": "cosine"},
        )
    return app_state["collection"]


def reset_collection():
    """Drop and recreate the shared collection (used by 'Clear session')."""
    try:
        chroma_client.delete_collection(name=COLLECTION_NAME)
    except Exception:
        pass
    app_state["collection"] = chroma_client.get_or_create_collection(
        name=COLLECTION_NAME,
        metadata={"hnsw:space": "cosine"},
    )

"""## PDF Extraction

Unchanged from the original: `PyPDF2`-based page-by-page text extraction, skipping empty pages, raising a
clear `ValueError` on corrupted or image-only PDFs.
"""

def extract_pdf_pages(pdf_path: str) -> List[Tuple[int, str]]:
    """Extract text from every page of a PDF.

    Returns a list of (page_number, page_text) tuples, 1-indexed. Raises ValueError
    if the PDF is corrupted, unreadable, or contains no extractable text at all.
    """
    if not pdf_path or not os.path.exists(pdf_path):
        raise ValueError("No PDF file was provided or the file could not be found.")

    try:
        reader = PdfReader(pdf_path)
    except PdfReadError as exc:
        raise ValueError(f"The PDF file appears to be corrupted: {exc}") from exc
    except Exception as exc:  # noqa: BLE001
        raise ValueError(f"Could not read the PDF file: {exc}") from exc

    if len(reader.pages) == 0:
        raise ValueError("The PDF file has no pages.")

    pages: List[Tuple[int, str]] = []
    for i, page in enumerate(reader.pages, start=1):
        try:
            text = page.extract_text() or ""
        except Exception:  # noqa: BLE001
            text = ""
        text = text.strip()
        if text:
            pages.append((i, text))

    if not pages:
        raise ValueError(
            "No extractable text was found in this PDF. It may be a scanned "
            "image-only document without an OCR text layer."
        )

    return pages

"""## Chunking

Unchanged: word-based sliding window, 200 words per chunk with 40-word overlap.
"""

def chunk_text(text: str, page_number: int, chunk_size: int = 200, overlap: int = 40) -> List[Dict]:
    """Split text into overlapping word-based chunks."""
    words = text.split()
    if not words:
        return []

    step = max(chunk_size - overlap, 1)
    chunks: List[Dict] = []

    for start in range(0, len(words), step):
        window = words[start:start + chunk_size]
        if not window:
            break
        chunks.append({"text": " ".join(window), "page": page_number})
        if start + chunk_size >= len(words):
            break

    return chunks


def chunk_pdf_pages(pages: List[Tuple[int, str]]) -> List[Dict]:
    """Chunk every page of an extracted PDF, keeping page numbers attached."""
    all_chunks: List[Dict] = []
    for page_number, page_text in pages:
        all_chunks.extend(chunk_text(page_text, page_number))
    return all_chunks

"""## Embeddings

Unchanged: normalized embeddings from the cached SentenceTransformer, used with cosine similarity.
"""

def embed_texts(texts: List[str]) -> List[List[float]]:
    """Embed a list of texts using the cached sentence-transformers model."""
    model = get_embedding_model()
    embeddings = model.encode(
        texts,
        show_progress_bar=False,
        convert_to_numpy=True,
        normalize_embeddings=True,
    )
    return embeddings.tolist()

"""## Indexing (multi-document)

Generalizes the original `index_pdf` to add a document to the *shared* collection instead of creating a
fresh collection per PDF, tagging every chunk with `doc_id` and `filename` so multiple PDFs can be queried
together and answers can be attributed to the right source.
"""

def index_pdf(pdf_path: str, filename: str) -> DocumentInfo:
    """Full indexing pipeline for one uploaded PDF, added to the shared collection."""
    pages = extract_pdf_pages(pdf_path)
    chunks = chunk_pdf_pages(pages)

    if not chunks:
        raise ValueError("No content could be chunked from this PDF.")

    doc_id = uuid.uuid4().hex
    collection = get_collection()

    texts = [c["text"] for c in chunks]
    embeddings = embed_texts(texts)

    ids = [f"{doc_id}_chunk_{i}" for i in range(len(chunks))]
    metadatas = [
        {"doc_id": doc_id, "filename": filename, "page": c["page"], "chunk_index": i}
        for i, c in enumerate(chunks)
    ]

    collection.add(ids=ids, embeddings=embeddings, documents=texts, metadatas=metadatas)

    doc_info = DocumentInfo(
        doc_id=doc_id,
        filename=filename,
        path=pdf_path,
        num_pages=len(pages),
        num_chunks=len(chunks),
    )
    app_state["documents"][doc_id] = doc_info
    return doc_info

"""## Document Management

New: remove a single document (deletes its vectors from the shared collection) or clear the whole session.
"""

def remove_document(doc_id: str) -> None:
    if doc_id not in app_state["documents"]:
        return
    collection = get_collection()
    try:
        collection.delete(where={"doc_id": doc_id})
    except Exception:
        pass
    del app_state["documents"][doc_id]


def clear_session() -> None:
    reset_collection()
    app_state["documents"] = {}
    app_state["last_question"] = None
    app_state["last_sources"] = []

"""## Retrieval

Same top-k similarity search as the original (`top_k=4`), now spanning every indexed document and
returning `filename` / `doc_id` / `page` alongside each chunk, plus a similarity score used for the
confidence badge.
"""

def retrieve_top_chunks(question: str, top_k: int = 4, doc_id: Optional[str] = None) -> List[Dict]:
    """Embed the question and retrieve the top-k most similar chunks.

    If `doc_id` is given, retrieval is scoped ONLY to chunks belonging to that document
    (this is the fix for the "selecting Profile.pdf still pulls from Session1.pdf" bug —
    previously every query searched the whole collection regardless of selection).
    Pass doc_id=None to search the entire library.
    """
    collection = get_collection()
    if collection.count() == 0:
        return []

    where = {"doc_id": doc_id} if doc_id else None

    # When filtering to one document, ask Chroma how many chunks that document actually has,
    # so n_results never exceeds it (Chroma errors if n_results > matching rows).
    if where:
        try:
            available = len(collection.get(where=where, include=[])["ids"])
        except Exception:
            available = top_k
        n_results = max(1, min(top_k, available))
        if available == 0:
            return []
    else:
        n_results = min(top_k, collection.count())

    question_embedding = embed_texts([question])[0]
    results = collection.query(
        query_embeddings=[question_embedding], n_results=n_results, where=where,
    )

    documents = results.get("documents", [[]])[0]
    metadatas = results.get("metadatas", [[]])[0]
    distances = results.get("distances", [[]])[0]

    retrieved = []
    for doc, meta, dist in zip(documents, metadatas, distances):
        similarity = max(0.0, min(1.0, 1.0 - dist))  # cosine space -> similarity
        retrieved.append({
            "text": doc,
            "page": meta.get("page"),
            "filename": meta.get("filename"),
            "doc_id": meta.get("doc_id"),
            "similarity": similarity,
        })
    return retrieved


def confidence_from_chunks(retrieved: List[Dict]) -> str:
    """Heuristic confidence label from the best retrieval similarity score.

    This is a simple, transparent heuristic (not a calibrated probability): it reflects how close the
    single best-matching chunk is to the question in embedding space, thresholds chosen for typical
    all-MiniLM-L6-v2 cosine similarity ranges on prose text.
    """
    if not retrieved:
        return "low"
    best = max(c["similarity"] for c in retrieved)
    if best >= 0.55:
        return "high"
    if best >= 0.35:
        return "medium"
    return "low"


def build_contextual_query(question: str, conversation_log: List[Dict], max_turns: int = 2) -> str:
    """Fold the last few turns into the retrieval query so pronouns like "it" or "that page"
    resolve to something embeddable, instead of searching for the bare word "it"."""
    if not conversation_log:
        return question
    recent = conversation_log[-max_turns:]
    context_bits = [f"{t['question']} {t['answer'][:160]}" for t in recent]
    return " ".join(context_bits) + " " + question

"""## Prompt Builder

Same grounding rules as the original prompt (answer only from context, never fabricate, be explicit when
the answer isn't in the document). The one addition is asking for a `Summary:` / `Answer:` structure so the
UI can show a short summary above the full answer — sources, page numbers, and confidence are computed
programmatically from retrieval metadata (not left to the model), so citations can never be hallucinated.
"""

PROMPT_TEMPLATE = """You are a helpful assistant answering questions about one or more documents.

{conversation_section}Answer ONLY using the context below. Never make up information.

Respond in exactly this structure:
Summary: <one short sentence summarizing the answer>
Answer: <the full, detailed answer>

If the answer is not contained in the context, set Summary to "Not found in the documents." and explain \
that honestly in Answer instead of guessing.

Context:
{retrieved_chunks}

Question:
{user_question}

Response:"""


def build_conversation_section(conversation_log: List[Dict], max_turns: int = 2) -> str:
    """Short recap of the last turns so the model can resolve references like "it" or "that page"."""
    if not conversation_log:
        return ""
    recent = conversation_log[-max_turns:]
    lines = ["Conversation so far (use this only to resolve references like \"it\" or \"that\"; "
             "the current question's own answer must still come from the Context below):"]
    for t in recent:
        lines.append(f"- Q: {t['question']}\n  A: {t['answer'][:200]}")
    return "\n".join(lines) + "\n\n"


def build_prompt(question: str, retrieved_chunks: List[Dict], conversation_log: Optional[List[Dict]] = None) -> str:
    """Build the grounded RAG prompt from retrieved chunks, the question, and recent conversation memory."""
    context_blocks = [
        f"[{chunk['filename']} — Page {chunk['page']}] {chunk['text']}" for chunk in retrieved_chunks
    ]
    context = "\n\n".join(context_blocks)
    conversation_section = build_conversation_section(conversation_log or [])
    return PROMPT_TEMPLATE.format(
        retrieved_chunks=context, user_question=question, conversation_section=conversation_section
    )


def parse_summary_answer(raw_text: str) -> Tuple[str, str]:
    """Parse the model's 'Summary: ... Answer: ...' structure; fall back gracefully if it didn't comply."""
    match = re.search(r"Summary:\s*(.*?)\n+Answer:\s*(.*)", raw_text, re.DOTALL)
    if match:
        summary = match.group(1).strip()
        answer = match.group(2).strip()
        return summary, answer
    return "", raw_text.strip()

"""## Streaming Generation

The original used a single blocking `pipeline()` call. To make the UI feel alive (Feature 5), this adds a
token-by-token generator using `TextIteratorStreamer`, running `model.generate` on a background thread —
the standard Hugging Face pattern for streaming. Same model, same greedy/low-temperature decoding settings
as the original (`do_sample=False`, `temperature=0.1`, `max_new_tokens=256`).
"""

NOT_FOUND_MESSAGE = "I couldn't find that information in the uploaded document(s)."


def stream_llm_response(prompt: str) -> Generator[str, None, None]:
    """Yield the growing generated text for `prompt`, token by token."""
    model, tokenizer = get_llm()
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    streamer = TextIteratorStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)

    generation_kwargs = dict(
        **inputs,
        streamer=streamer,
        max_new_tokens=256,
        do_sample=False,
        temperature=0.1,
        pad_token_id=tokenizer.eos_token_id,
    )

    thread = threading.Thread(target=model.generate, kwargs=generation_kwargs)
    thread.start()

    partial = ""
    for token_text in streamer:
        partial += token_text
        yield partial
    thread.join()

"""## Answer Pipeline

Orchestrates retrieval → prompt → streaming generation, yielding staged status updates (Feature 6) so the
UI can show "Searching documents...", "Thinking...", "Writing answer..." etc. Every yielded dict has the
same shape so the Gradio callback can consume it uniformly.
"""

def answer_pipeline(question: str, doc_filter: Optional[str] = None) -> Generator[Dict, None, None]:
    """Generator yielding {'stage', 'partial_answer', 'summary', 'sources', 'confidence', 'done'} dicts.

    `doc_filter` is the doc_id to restrict retrieval to. Pass None to search the entire library.
    Conversation memory (recent Q/A turns from app_state["conversation_log"]) is folded into both
    the retrieval query and the prompt, so follow-ups like "explain it more simply" work.
    """
    base = {"partial_answer": "", "summary": "", "sources": [], "confidence": None, "done": False}

    if not question or not question.strip():
        yield {**base, "stage": "idle", "partial_answer": "Please enter a question.", "done": True}
        return

    if len(question.split()) > 200:
        msg = "Your question is quite long. Please shorten it to under 200 words so it can be processed effectively."
        yield {**base, "stage": "idle", "partial_answer": msg, "done": True}
        return

    if not app_state["documents"]:
        msg = "⚠️ Please upload and index at least one PDF before asking a question."
        yield {**base, "stage": "idle", "partial_answer": msg, "done": True}
        return

    if doc_filter and doc_filter not in app_state["documents"]:
        doc_filter = None  # selected document was removed since the filter was set

    conversation_log = app_state.get("conversation_log", [])

    yield {**base, "stage": "🔍 Searching documents..."}
    contextual_query = build_contextual_query(question, conversation_log)
    retrieved = retrieve_top_chunks(contextual_query, top_k=4, doc_id=doc_filter)

    if not retrieved:
        msg = NOT_FOUND_MESSAGE
        if doc_filter:
            filename = app_state["documents"][doc_filter].filename
            msg = f"I couldn't find that information in **{filename}**. Try switching search scope to Entire Library."
        yield {**base, "stage": "idle", "partial_answer": msg, "confidence": "low", "done": True}
        return

    confidence = confidence_from_chunks(retrieved)

    yield {**base, "stage": "🤖 Thinking...", "sources": retrieved, "confidence": confidence}

    prompt = build_prompt(question, retrieved, conversation_log)

    partial_raw = ""
    for partial_raw in stream_llm_response(prompt):
        summary, answer = parse_summary_answer(partial_raw)
        yield {
            "stage": "✨ Writing answer...",
            "partial_answer": answer if answer else partial_raw,
            "summary": summary,
            "sources": retrieved,
            "confidence": confidence,
            "done": False,
        }

    summary, answer = parse_summary_answer(partial_raw)
    if not answer.strip():
        answer = NOT_FOUND_MESSAGE
        confidence = "low"

    app_state["conversation_log"].append({
        "question": question,
        "answer": answer,
        "sources": retrieved,
        "confidence": confidence,
        "timestamp": datetime.now().strftime("%H:%M:%S"),
    })

    yield {
        "stage": "done",
        "partial_answer": answer,
        "summary": summary,
        "sources": retrieved,
        "confidence": confidence,
        "done": True,
    }

"""## PDF Preview Rendering

New: renders a single PDF page to an image for the right-hand preview panel. When a citation is clicked,
the matching snippet is located on the page with `page.search_for(...)` and highlighted before rendering —
with a fallback that shortens the search phrase if the full chunk doesn't match verbatim (chunks can span
line breaks or minor extraction artifacts).
"""

def _find_highlight_rects(page: "fitz.Page", snippet: str) -> List["fitz.Rect"]:
    words = snippet.split()
    for n in (14, 10, 6, 3):
        phrase = " ".join(words[:n])
        if not phrase:
            continue
        rects = page.search_for(phrase)
        if rects:
            return rects
    return []


def render_pdf_page(doc_id: str, page_number: int, highlight_snippet: Optional[str] = None, zoom: float = 1.7):
    """Return a PIL Image of the given 1-indexed page, with an optional highlighted snippet.

    Note: this returns a flattened raster image (Gradio's Image component), so the highlight can't
    fade with a CSS transition the way a DOM overlay could — it's baked into the rendered pixels
    each time you click a citation or search result, which is what "real" highlighting means here.
    """
    doc_info = app_state["documents"].get(doc_id)
    if not doc_info:
        return None

    pdf_doc = fitz.open(doc_info.path)
    try:
        idx = max(0, min(page_number - 1, len(pdf_doc) - 1))
        page = pdf_doc[idx]

        if highlight_snippet:
            for rect in _find_highlight_rects(page, highlight_snippet):
                annot = page.add_highlight_annot(rect)
                annot.set_colors(stroke=(0.99, 0.85, 0.35))
                annot.update()

        mat = fitz.Matrix(zoom, zoom)
        pix = page.get_pixmap(matrix=mat)
        image = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
        return image
    finally:
        pdf_doc.close()


def search_in_pdf(query: str, doc_id: Optional[str] = None, max_results: int = 8) -> List[Dict]:
    """Full-text search across page images (exact substring, via PyMuPDF's built-in search_for).

    doc_id=None searches every uploaded document ("Entire Library"); otherwise only that one
    ("Current Document"). Returns one entry per matching page, most-matches first.
    """
    results: List[Dict] = []
    if not query or not query.strip():
        return results

    docs = (
        [app_state["documents"][doc_id]] if doc_id and doc_id in app_state["documents"]
        else list(app_state["documents"].values())
    )

    for doc_info in docs:
        try:
            pdf_doc = fitz.open(doc_info.path)
        except Exception:
            continue
        try:
            for i, page in enumerate(pdf_doc, start=1):
                rects = page.search_for(query)
                if rects:
                    results.append({
                        "doc_id": doc_info.doc_id,
                        "filename": doc_info.filename,
                        "page": i,
                        "count": len(rects),
                    })
        finally:
            pdf_doc.close()

    results.sort(key=lambda r: r["count"], reverse=True)
    return results[:max_results]

"""## UI Helper Functions

Small pure functions that turn app state into the HTML/markdown fragments the UI needs: the sidebar
document list, the collection stats grid, and the confidence badge.
"""

def render_document_list_html() -> str:
    docs = list(app_state["documents"].values())
    if not docs:
        return '<div style="color:#7E82A0; font-size:12.5px; padding:4px 2px;">No documents indexed yet.</div>'
    active_id = app_state.get("active_filter_doc_id")
    cards = []
    for d in docs:
        is_active = app_state.get("search_scope") == "single" and d.doc_id == active_id
        active_class = " p-doc-active" if is_active else ""
        active_tag = '<div class="p-doc-active-tag">● Active filter</div>' if is_active else ""
        cards.append(
            f'<div class="p-doc-card{active_class}"><div class="p-doc-name">📄 {html.escape(d.filename)}</div>'
            f'<div class="p-doc-meta">{d.num_pages} pages · {d.num_chunks} chunks</div>{active_tag}</div>'
        )
    return "".join(cards)


def render_stats_html() -> str:
    docs = list(app_state["documents"].values())
    total_files = len(docs)
    total_pages = sum(d.num_pages for d in docs)
    total_chunks = sum(d.num_chunks for d in docs)
    gpu_ok = torch.cuda.is_available()
    gpu_color = "#22C55E" if gpu_ok else "#EF4444"
    gpu_label = torch.cuda.get_device_name(0) if gpu_ok else "CPU (slow)"

    scope = app_state.get("search_scope", "library")
    if scope == "single" and app_state.get("active_filter_doc_id") in app_state["documents"]:
        scope_label = f"🎯 {app_state['documents'][app_state['active_filter_doc_id']].filename}"
    else:
        scope_label = "🌐 Entire Library"

    return f"""
    <div class="p-stat-grid">
      <div class="p-stat-box"><div class="p-stat-value">{total_files}</div><div class="p-stat-label">Files</div></div>
      <div class="p-stat-box"><div class="p-stat-value">{total_pages}</div><div class="p-stat-label">Pages</div></div>
      <div class="p-stat-box"><div class="p-stat-value">{total_chunks}</div><div class="p-stat-label">Chunks</div></div>
      <div class="p-stat-box"><div class="p-stat-value" style="font-size:12px;">{EMBEDDING_MODEL_NAME}</div><div class="p-stat-label">Embeddings</div></div>
    </div>
    <div class="p-stat-box" style="margin-top:8px;">
      <span class="p-gpu-dot" style="background:{gpu_color};"></span>
      <span style="font-size:12.5px; color:#EDEDF3;">{html.escape(gpu_label)}</span>
    </div>
    <div class="p-scope-badge">{html.escape(scope_label)} search scope</div>
    """


def confidence_badge_html(confidence: Optional[str]) -> str:
    if not confidence:
        return ""
    labels = {"high": "High confidence", "medium": "Medium confidence", "low": "Low confidence"}
    classes = {"high": "p-conf-high", "medium": "p-conf-medium", "low": "p-conf-low"}
    return f'<span class="p-confidence-badge {classes[confidence]}">{labels[confidence]}</span>'


def format_assistant_message(summary: str, answer: str, confidence: Optional[str], streaming: bool = False) -> str:
    parts = []
    if summary and summary.lower() != "not found in the documents.":
        parts.append(f"**{summary}**")
    cursor = ' <span class="p-stream-cursor"></span>' if streaming else ""
    parts.append(answer + cursor)
    msg = "\n\n".join(parts)
    if confidence and not streaming:
        msg += f"\n\n{confidence_badge_html(confidence)}"
    return msg


def source_card_label(source: Dict) -> str:
    snippet = source["text"][:70].strip()
    if len(source["text"]) > 70:
        snippet += "…"
    score_pct = round(source["similarity"] * 100)
    return f"📄 {source['filename']} · p.{source['page']} · {score_pct}% match\n{snippet}"


# ---------------------------------------------------------------------------
# Smart prompt chips — a curated pool of document-analysis prompts. These are
# generic-but-useful across most PDFs; swap `get_dynamic_chips` for an LLM call
# (e.g. "read the first page and propose 6 chip prompts") if you want chips that
# are genuinely tailored to each document's content rather than its presence.
# ---------------------------------------------------------------------------
CHIP_POOL = [
    ("📝 Summarize", "Summarize this document in a few clear paragraphs."),
    ("💡 Explain", "Explain the main ideas of this document in simple terms."),
    ("❓ Create Quiz", "Create a short 5-question quiz based on this document, with answers."),
    ("📖 Find Definitions", "Find and explain the key terms and definitions in this document."),
    ("📅 Extract Dates", "List all dates, deadlines, or events mentioned in this document."),
    ("🗂️ List Key Topics", "List the main topics covered in this document, as bullet points."),
    ("🎤 Interview Questions", "Generate 5 interview questions someone could be asked based on this document."),
    ("🧠 Explain Difficult Concepts", "Identify and explain the most difficult concepts in this document, simply."),
    ("⚖️ Compare Sections", "Compare and contrast the main sections or parts of this document."),
    ("📓 Revision Notes", "Turn this document into concise revision notes."),
]

MAX_CHIPS = 6


def get_dynamic_chips(doc_filename: Optional[str] = None, max_chips: int = MAX_CHIPS) -> List[Tuple[str, str]]:
    """Pick a stable, useful subset of chips. Rotates slightly by filename so different
    documents don't always show the exact same six prompts."""
    if not doc_filename:
        return CHIP_POOL[:max_chips]
    offset = sum(ord(c) for c in doc_filename) % len(CHIP_POOL)
    rotated = CHIP_POOL[offset:] + CHIP_POOL[:offset]
    # Always keep Summarize first — it's the most useful default entry point.
    rotated = sorted(rotated, key=lambda c: c != CHIP_POOL[0])
    return rotated[:max_chips]


# ---------------------------------------------------------------------------
# Export
# ---------------------------------------------------------------------------
def export_conversation_markdown() -> Optional[str]:
    log = app_state.get("conversation_log", [])
    if not log:
        return None
    lines = [f"# {PLATYPUS_NAME} — Conversation Export",
             f"_Exported {datetime.now().strftime('%Y-%m-%d %H:%M')}_", ""]
    for turn in log:
        lines.append(f"### 🕐 {turn['timestamp']}")
        lines.append(f"**Q:** {turn['question']}")
        lines.append("")
        lines.append(f"**A:** {turn['answer']}")
        if turn.get("confidence"):
            lines.append(f"\n_Confidence: {turn['confidence']}_")
        if turn.get("sources"):
            lines.append("\n**Sources:**")
            for s in turn["sources"]:
                lines.append(f"- {s['filename']} (page {s['page']}, {round(s['similarity']*100)}% match)")
        lines.append("\n---\n")

    path = os.path.join("/tmp", f"platypus_export_{uuid.uuid4().hex[:8]}.md")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return path


def export_conversation_pdf() -> Optional[str]:
    log = app_state.get("conversation_log", [])
    if not log:
        return None

    doc = fitz.open()
    page_w, page_h = fitz.paper_size("a4")
    margin = 48
    line_h = 14
    y = margin
    page = doc.new_page(width=page_w, height=page_h)

    def new_page():
        nonlocal page, y
        page = doc.new_page(width=page_w, height=page_h)
        y = margin

    def write_line(text: str, size: float = 10.5, color=(0.07, 0.07, 0.1), bold: bool = False):
        nonlocal y
        wrapped = textwrap.wrap(text, width=95) or [""]
        for line in wrapped:
            if y > page_h - margin:
                new_page()
            fontname = "helv" if not bold else "hebo"
            page.insert_text((margin, y), line, fontsize=size, fontname=fontname, color=color)
            y += line_h

    write_line(f"{PLATYPUS_NAME} — Conversation Export", size=18, bold=True, color=(0.36, 0.37, 0.93))
    write_line(f"Exported {datetime.now().strftime('%Y-%m-%d %H:%M')}", size=9, color=(0.4, 0.4, 0.5))
    y += 8

    for turn in log:
        write_line(f"[{turn['timestamp']}]", size=9, color=(0.4, 0.4, 0.5))
        write_line(f"Q: {turn['question']}", bold=True)
        write_line(f"A: {turn['answer']}")
        if turn.get("confidence"):
            write_line(f"Confidence: {turn['confidence']}", size=9, color=(0.4, 0.4, 0.5))
        for s in turn.get("sources", []):
            write_line(f"  Source: {s['filename']} (p.{s['page']}, {round(s['similarity']*100)}% match)",
                       size=9, color=(0.4, 0.4, 0.5))
        y += 10

    path = os.path.join("/tmp", f"platypus_export_{uuid.uuid4().hex[:8]}.pdf")
    doc.save(path)
    doc.close()
    return path

"""## Gradio Callbacks

Every callback below is a thin adapter between the pure functions above and Gradio components. Upload and
ask are generators so Gradio streams intermediate states (loading messages, then tokens) to the UI.
"""

MAX_SOURCE_CARDS = 4
MAX_SEARCH_RESULTS = 8


def _doc_choices() -> List[Tuple[str, str]]:
    return [(d.filename, d.doc_id) for d in app_state["documents"].values()]


def _chip_updates_and_prompts(doc_id: Optional[str]):
    filename = app_state["documents"][doc_id].filename if doc_id in app_state.get("documents", {}) else None
    chips = get_dynamic_chips(filename, max_chips=MAX_CHIPS)
    labels = [c[0] for c in chips]
    prompts = [c[1] for c in chips]
    updates = [
        gr.update(value=labels[i], visible=True) if i < len(labels) else gr.update(visible=False)
        for i in range(MAX_CHIPS)
    ]
    return updates, prompts


def handle_upload(files) -> Generator[Tuple, None, None]:
    """Index one or more uploaded PDFs, yielding staged status updates."""
    if not files:
        chip_updates, chip_prompts = _chip_updates_and_prompts(app_state.get("active_filter_doc_id"))
        yield ("⚠️ No PDF uploaded. Please choose at least one file.",
               render_document_list_html(), render_stats_html(), gr.update(), gr.update(), *chip_updates, chip_prompts)
        return

    file_paths = [f if isinstance(f, str) else f.name for f in files]
    total = len(file_paths)
    chip_updates, chip_prompts = _chip_updates_and_prompts(app_state.get("active_filter_doc_id"))

    for i, path in enumerate(file_paths, start=1):
        filename = os.path.basename(path)
        stage_prefix = f"({i}/{total}) {filename}: "

        for stage in ["📄 Reading document...", "✂️ Chunking pages...",
                      "🧠 Creating embeddings...", "📚 Building knowledge base..."]:
            yield (stage_prefix + stage, render_document_list_html(), render_stats_html(),
                   gr.update(), gr.update(), *chip_updates, chip_prompts)

        try:
            index_pdf(path, filename)
            status = f'<span class="p-success-flash">✅ {filename} indexed successfully.</span>'
        except ValueError as exc:
            status = f"❌ {filename}: {exc}"
        except Exception as exc:  # noqa: BLE001
            status = f"❌ {filename}: unexpected error — {exc}"

        yield (status, render_document_list_html(), render_stats_html(),
               gr.update(), gr.update(), *chip_updates, chip_prompts)

    doc_choices = _doc_choices()
    if not app_state.get("active_filter_doc_id") and doc_choices:
        app_state["active_filter_doc_id"] = doc_choices[0][1]
    chip_updates, chip_prompts = _chip_updates_and_prompts(app_state.get("active_filter_doc_id"))

    yield (
        f"✅ Indexing complete. {len(app_state['documents'])} document(s) ready.",
        render_document_list_html(),
        render_stats_html(),
        gr.update(choices=doc_choices, value=(doc_choices[0][1] if doc_choices else None)),
        gr.update(choices=doc_choices, value=app_state.get("active_filter_doc_id")),
        *chip_updates, chip_prompts,
    )


def handle_remove(doc_id: Optional[str]):
    if doc_id:
        remove_document(doc_id)
    if app_state.get("active_filter_doc_id") not in app_state["documents"]:
        remaining = _doc_choices()
        app_state["active_filter_doc_id"] = remaining[0][1] if remaining else None
    doc_choices = _doc_choices()
    chip_updates, chip_prompts = _chip_updates_and_prompts(app_state.get("active_filter_doc_id"))
    return (
        render_document_list_html(),
        render_stats_html(),
        gr.update(choices=doc_choices, value=(doc_choices[0][1] if doc_choices else None)),
        gr.update(choices=doc_choices, value=(doc_choices[0][1] if doc_choices else None)),
        gr.update(choices=doc_choices, value=app_state.get("active_filter_doc_id")),
        *chip_updates, chip_prompts,
    )


def handle_clear_session():
    clear_session()
    app_state["search_scope"] = "library"
    app_state["active_filter_doc_id"] = None
    app_state["conversation_log"] = []
    app_state["last_search_results"] = []
    chip_updates, chip_prompts = _chip_updates_and_prompts(None)
    return (
        [],  # chat history
        render_document_list_html(),
        render_stats_html(),
        gr.update(choices=[], value=None),
        gr.update(choices=[], value=None),
        gr.update(choices=[], value=None),
        None,  # preview image
        *[gr.update(visible=False, value="") for _ in range(MAX_SOURCE_CARDS)],
        *chip_updates, chip_prompts,
        *[gr.update(visible=False, value="") for _ in range(MAX_SEARCH_RESULTS)],
    )


def _empty_source_updates():
    return [gr.update(visible=False, value="") for _ in range(MAX_SOURCE_CARDS)]


def _source_updates(sources: List[Dict]):
    updates = []
    for i in range(MAX_SOURCE_CARDS):
        if i < len(sources):
            updates.append(gr.update(visible=True, value=source_card_label(sources[i])))
        else:
            updates.append(gr.update(visible=False, value=""))
    return updates


def handle_ask(question: str, history):
    """Stream an answer into the chatbot, yielding (history, textbox, status, *source_buttons)."""
    history = history or []

    if not question or not question.strip():
        yield history, question, "", *_empty_source_updates()
        return

    app_state["last_question"] = question
    history = history + [{"role": "user", "content": question}, {"role": "assistant", "content": ""}]

    doc_filter = app_state.get("active_filter_doc_id") if app_state.get("search_scope") == "single" else None

    for update in answer_pipeline(question, doc_filter=doc_filter):
        stage = update["stage"]
        status_html = (
            f'<div class="p-loading-row"><span class="p-loading-dot"></span>{html.escape(stage)}</div>'
            if stage not in ("idle", "done") else ""
        )

        if update["partial_answer"]:
            history[-1]["content"] = format_assistant_message(
                update.get("summary", ""), update["partial_answer"], update.get("confidence"),
                streaming=not update["done"],
            )

        source_updates = _source_updates(update["sources"]) if update["sources"] else _empty_source_updates()
        app_state["last_sources"] = update["sources"]

        yield history, ("" if update["done"] else question), status_html, *source_updates


def handle_regenerate(history):
    question = app_state.get("last_question")
    if not question:
        yield history, *_empty_source_updates()
        return
    # Drop the previous assistant turn (and the user turn we're about to re-add) before regenerating.
    trimmed = history[:-2] if len(history) >= 2 else []
    if app_state.get("conversation_log"):
        app_state["conversation_log"].pop()  # remove the stale logged turn we're about to redo
    for h, _, _, *sources in handle_ask(question, trimmed):
        yield h, *sources


def handle_clear_chat():
    app_state["last_question"] = None
    app_state["last_sources"] = []
    app_state["conversation_log"] = []
    return [], "", *_empty_source_updates()


def handle_chip_click(index: int, chip_prompts: List[str], history):
    if not chip_prompts or index >= len(chip_prompts):
        yield history, "", "", *_empty_source_updates()
        return
    prompt_text = chip_prompts[index]
    for h, q, s, *sources in handle_ask(prompt_text, history):
        yield h, q, s, *sources


def handle_source_click(index: int):
    sources = app_state.get("last_sources", [])
    if index >= len(sources):
        return gr.update(), gr.update(), None
    source = sources[index]
    image = render_pdf_page(source["doc_id"], source["page"], highlight_snippet=source["text"])
    return source["doc_id"], source["page"], image


def handle_preview_nav(doc_id: Optional[str], page_number: Optional[int]):
    if not doc_id or not page_number:
        return None
    image = render_pdf_page(doc_id, int(page_number))
    return image


def handle_doc_select(doc_id: Optional[str]):
    if not doc_id:
        return 1, None
    image = render_pdf_page(doc_id, 1)
    return 1, image


def handle_scope_change(scope_label: str):
    app_state["search_scope"] = "single" if scope_label == "Selected Document" else "library"
    return render_document_list_html(), render_stats_html()


def handle_active_filter_change(doc_id: Optional[str]):
    app_state["active_filter_doc_id"] = doc_id
    chip_updates, chip_prompts = _chip_updates_and_prompts(doc_id)
    return (render_document_list_html(), render_stats_html(), *chip_updates, chip_prompts)


def _empty_search_result_updates():
    return [gr.update(visible=False, value="") for _ in range(MAX_SEARCH_RESULTS)]


def handle_search_pdf(query: str, scope_label: str):
    if not query or not query.strip():
        return _empty_search_result_updates()
    doc_id = app_state.get("active_filter_doc_id") if scope_label == "Selected Document" else None
    results = search_in_pdf(query, doc_id=doc_id, max_results=MAX_SEARCH_RESULTS)
    app_state["last_search_query"] = query
    app_state["last_search_results"] = results
    updates = []
    for i in range(MAX_SEARCH_RESULTS):
        if i < len(results):
            r = results[i]
            label = f"📄 {r['filename']} · p.{r['page']} · {r['count']} match(es)"
            updates.append(gr.update(visible=True, value=label))
        else:
            updates.append(gr.update(visible=False, value=""))
    return updates


def handle_search_result_click(index: int):
    results = app_state.get("last_search_results", [])
    if index >= len(results):
        return gr.update(), gr.update(), None
    r = results[index]
    image = render_pdf_page(r["doc_id"], r["page"], highlight_snippet=app_state.get("last_search_query", ""))
    return r["doc_id"], r["page"], image


def handle_export_markdown():
    path = export_conversation_markdown()
    if not path:
        gr.Warning("Nothing to export yet — ask a question first.")
        return gr.update(value=None, visible=False)
    return gr.update(value=path, visible=True)


def handle_export_pdf():
    path = export_conversation_pdf()
    if not path:
        gr.Warning("Nothing to export yet — ask a question first.")
        return gr.update(value=None, visible=False)
    return gr.update(value=path, visible=True)

"""## Gradio UI Layout

Three panels: a dark sidebar (branding, uploads, document list, stats), a main conversation panel, and a
right-hand PDF preview synced to whichever citation was last clicked.
"""

with gr.Blocks(title=f"{PLATYPUS_NAME} — {PLATYPUS_TAGLINE}", css=PLATYPUS_CSS, theme=gr.themes.Base(
    primary_hue=gr.themes.colors.indigo, neutral_hue=gr.themes.colors.slate, font=["Inter", "sans-serif"]
)) as demo:

    initial_chip_updates, initial_chip_prompts = _chip_updates_and_prompts(None)
    chip_prompts_state = gr.State(initial_chip_prompts)

    with gr.Row(equal_height=True):
        # ---------------- Sidebar (20%) ----------------
        with gr.Column(scale=4, elem_id="platypus-sidebar"):
            with gr.Row():
                gr.HTML(f"""
                    <div class="p-logo-row">{PLATYPUS_LOGO_SVG}<span class="p-wordmark">{PLATYPUS_NAME}</span></div>
                    <div class="p-tagline">{PLATYPUS_TAGLINE}</div>
                """)
            dark_toggle_btn = gr.Button("🌙 Toggle theme", elem_classes=["p-theme-toggle"], size="sm")

            gr.Markdown('<div class="p-section-label">Upload PDFs</div>')
            pdf_upload = gr.File(label=None, file_types=[".pdf"], file_count="multiple", show_label=False)
            upload_status = gr.HTML("")

            gr.Markdown('<div class="p-section-label">Documents</div>')
            doc_list_html = gr.HTML(render_document_list_html())

            remove_selector = gr.Dropdown(choices=[], label="Select a document", value=None, interactive=True)
            with gr.Row():
                remove_btn = gr.Button("🗑 Remove", elem_classes=["p-ghost-btn"], size="sm")
                clear_session_btn = gr.Button("Clear session", elem_classes=["p-ghost-btn"], size="sm")

            gr.Markdown('<div class="p-section-label">Search Mode</div>')
            search_scope_radio = gr.Radio(
                choices=["Entire Library", "Selected Document"], value="Entire Library",
                label=None, show_label=False,
            )
            active_filter_selector = gr.Dropdown(
                choices=[], value=None, label="Retrieval filter (used when scope = Selected Document)",
            )

            gr.Markdown('<div class="p-section-label">Collection Stats</div>')
            stats_html = gr.HTML(render_stats_html())

            gr.Markdown('<div class="p-section-label">Export</div>')
            with gr.Row():
                export_md_btn = gr.Button("⬇ Markdown", elem_classes=["p-ghost-btn"], size="sm")
                export_pdf_btn = gr.Button("⬇ PDF", elem_classes=["p-ghost-btn"], size="sm")
            export_file = gr.File(label="Download", visible=False)

        # ---------------- Main panel (55%) ----------------
        with gr.Column(scale=11):
            chatbot = gr.Chatbot(
                label=None, show_label=False, height=460,
                elem_id="platypus-chat", buttons=["copy", "copy_all"], avatar_images=(None, None),
                allow_tags=["span", "mark", "div"],
                placeholder=f"### 🦫 {PLATYPUS_TAGLINE}\nUpload a PDF on the left to get started.",
            )
            status_row = gr.HTML("")

            with gr.Row():
                source_buttons = [
                    gr.Button("", visible=False, elem_classes=["p-source-card"], size="sm")
                    for _ in range(MAX_SOURCE_CARDS)
                ]

            with gr.Row():
                chip_buttons = [
                    gr.Button(
                        initial_chip_updates[i]["value"] if i < len(initial_chip_prompts) else "",
                        visible=(i < len(initial_chip_prompts)),
                        elem_classes=["p-chip-btn"], size="sm",
                    )
                    for i in range(MAX_CHIPS)
                ]

            with gr.Row():
                question_box = gr.Textbox(
                    placeholder="Ask a question about your documents…", show_label=False, scale=8,
                    container=False,
                )
                ask_button = gr.Button("Send", elem_classes=["p-primary-btn"], scale=1)

            with gr.Row():
                regenerate_btn = gr.Button("↻ Regenerate", elem_classes=["p-ghost-btn"], size="sm")
                clear_chat_btn = gr.Button("Clear conversation", elem_classes=["p-ghost-btn"], size="sm")

        # ---------------- Right panel: PDF preview + search (25%) ----------------
        with gr.Column(scale=5, elem_id="platypus-preview"):
            gr.HTML('<div class="p-preview-header">PDF Preview</div>'
                    '<div class="p-preview-sub">Click a source card to jump to that page.</div>')
            preview_doc_selector = gr.Dropdown(choices=[], label="Document", value=None)
            with gr.Row():
                prev_page_btn = gr.Button("◀", size="sm", elem_classes=["p-ghost-btn"])
                page_number_box = gr.Number(value=1, precision=0, label="Page", scale=2)
                next_page_btn = gr.Button("▶", size="sm", elem_classes=["p-ghost-btn"])
            preview_image = gr.Image(label=None, show_label=False, height=380)

            gr.Markdown('<div class="p-section-label">Search Inside PDF</div>')
            with gr.Row():
                pdf_search_box = gr.Textbox(placeholder="Find text…", show_label=False, container=False, scale=3)
                pdf_search_btn = gr.Button("🔎", size="sm", scale=1, elem_classes=["p-ghost-btn"])
            search_result_buttons = [
                gr.Button("", visible=False, elem_classes=["p-search-result"], size="sm")
                for _ in range(MAX_SEARCH_RESULTS)
            ]

    # ---------------- Wiring ----------------

    dark_toggle_btn.click(fn=None, inputs=None, outputs=None, js=TOGGLE_DARK_JS)

    pdf_upload.change(
        fn=handle_upload, inputs=pdf_upload,
        outputs=[upload_status, doc_list_html, stats_html, remove_selector, active_filter_selector,
                 *chip_buttons, chip_prompts_state],
    ).then(
        fn=lambda: gr.update(choices=_doc_choices()),
        outputs=preview_doc_selector,
    )

    remove_btn.click(
        fn=handle_remove, inputs=remove_selector,
        outputs=[doc_list_html, stats_html, remove_selector, preview_doc_selector, active_filter_selector,
                 *chip_buttons, chip_prompts_state],
    )

    clear_session_btn.click(
        fn=handle_clear_session,
        outputs=[chatbot, doc_list_html, stats_html, remove_selector, preview_doc_selector, active_filter_selector,
                 preview_image, *source_buttons, *chip_buttons, chip_prompts_state, *search_result_buttons],
    )

    ask_button.click(
        fn=handle_ask, inputs=[question_box, chatbot],
        outputs=[chatbot, question_box, status_row, *source_buttons],
    )
    question_box.submit(
        fn=handle_ask, inputs=[question_box, chatbot],
        outputs=[chatbot, question_box, status_row, *source_buttons],
    )

    regenerate_btn.click(
        fn=handle_regenerate, inputs=chatbot, outputs=[chatbot, *source_buttons],
    )
    clear_chat_btn.click(
        fn=handle_clear_chat, outputs=[chatbot, status_row, *source_buttons],
    )

    for i, btn in enumerate(chip_buttons):
        btn.click(
            fn=partial(handle_chip_click, i), inputs=[chip_prompts_state, chatbot],
            outputs=[chatbot, question_box, status_row, *source_buttons],
        )

    for i, btn in enumerate(source_buttons):
        btn.click(
            fn=handle_source_click, inputs=gr.State(i),
            outputs=[preview_doc_selector, page_number_box, preview_image],
        )

    preview_doc_selector.change(
        fn=handle_doc_select, inputs=preview_doc_selector, outputs=[page_number_box, preview_image],
    )
    page_number_box.change(
        fn=handle_preview_nav, inputs=[preview_doc_selector, page_number_box], outputs=preview_image,
    )
    prev_page_btn.click(
        fn=lambda p: max(1, int(p or 1) - 1), inputs=page_number_box, outputs=page_number_box,
    )
    next_page_btn.click(
        fn=lambda p: int(p or 1) + 1, inputs=page_number_box, outputs=page_number_box,
    )

    search_scope_radio.change(
        fn=handle_scope_change, inputs=search_scope_radio, outputs=[doc_list_html, stats_html],
    )
    active_filter_selector.change(
        fn=handle_active_filter_change, inputs=active_filter_selector,
        outputs=[doc_list_html, stats_html, *chip_buttons, chip_prompts_state],
    )

    pdf_search_btn.click(
        fn=handle_search_pdf, inputs=[pdf_search_box, search_scope_radio], outputs=search_result_buttons,
    )
    pdf_search_box.submit(
        fn=handle_search_pdf, inputs=[pdf_search_box, search_scope_radio], outputs=search_result_buttons,
    )
    for i, btn in enumerate(search_result_buttons):
        btn.click(
            fn=partial(handle_search_result_click, i),
            outputs=[preview_doc_selector, page_number_box, preview_image],
        )

    export_md_btn.click(fn=handle_export_markdown, outputs=export_file)
    export_pdf_btn.click(fn=handle_export_pdf, outputs=export_file)

"""## Launch"""

demo.launch(debug=True, share=True)